// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.3
// source: protobuf/rps.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Moves int32

const (
	Moves_Rock     Moves = 0
	Moves_Paper    Moves = 1
	Moves_Scissors Moves = 2
	Moves_Quit     Moves = 3
)

// Enum value maps for Moves.
var (
	Moves_name = map[int32]string{
		0: "Rock",
		1: "Paper",
		2: "Scissors",
		3: "Quit",
	}
	Moves_value = map[string]int32{
		"Rock":     0,
		"Paper":    1,
		"Scissors": 2,
		"Quit":     3,
	}
)

func (x Moves) Enum() *Moves {
	p := new(Moves)
	*p = x
	return p
}

func (x Moves) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Moves) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_rps_proto_enumTypes[0].Descriptor()
}

func (Moves) Type() protoreflect.EnumType {
	return &file_protobuf_rps_proto_enumTypes[0]
}

func (x Moves) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Moves.Descriptor instead.
func (Moves) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_rps_proto_rawDescGZIP(), []int{0}
}

type Result int32

const (
	Result_Win  Result = 0
	Result_Lose Result = 1
	Result_Draw Result = 2
)

// Enum value maps for Result.
var (
	Result_name = map[int32]string{
		0: "Win",
		1: "Lose",
		2: "Draw",
	}
	Result_value = map[string]int32{
		"Win":  0,
		"Lose": 1,
		"Draw": 2,
	}
)

func (x Result) Enum() *Result {
	p := new(Result)
	*p = x
	return p
}

func (x Result) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Result) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_rps_proto_enumTypes[1].Descriptor()
}

func (Result) Type() protoreflect.EnumType {
	return &file_protobuf_rps_proto_enumTypes[1]
}

func (x Result) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Result.Descriptor instead.
func (Result) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_rps_proto_rawDescGZIP(), []int{1}
}

type Action struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId int32 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Move     Moves `protobuf:"varint,2,opt,name=move,proto3,enum=protobuf.Moves" json:"move,omitempty"`
}

func (x *Action) Reset() {
	*x = Action{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_rps_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_rps_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_protobuf_rps_proto_rawDescGZIP(), []int{0}
}

func (x *Action) GetPlayerId() int32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *Action) GetMove() Moves {
	if x != nil {
		return x.Move
	}
	return Moves_Rock
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Res Result `protobuf:"varint,2,opt,name=res,proto3,enum=protobuf.Result" json:"res,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_rps_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_rps_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_protobuf_rps_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *Response) GetRes() Result {
	if x != nil {
		return x.Res
	}
	return Result_Win
}

var File_protobuf_rps_proto protoreflect.FileDescriptor

var file_protobuf_rps_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x72, 0x70, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x22, 0x4a,
	0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x04, 0x6d, 0x6f, 0x76, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d,
	0x6f, 0x76, 0x65, 0x73, 0x52, 0x04, 0x6d, 0x6f, 0x76, 0x65, 0x22, 0x40, 0x0a, 0x08, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x22, 0x0a, 0x03, 0x72, 0x65, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x03, 0x72, 0x65, 0x73, 0x2a, 0x34, 0x0a, 0x05,
	0x4d, 0x6f, 0x76, 0x65, 0x73, 0x12, 0x08, 0x0a, 0x04, 0x52, 0x6f, 0x63, 0x6b, 0x10, 0x00, 0x12,
	0x09, 0x0a, 0x05, 0x50, 0x61, 0x70, 0x65, 0x72, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x53, 0x63,
	0x69, 0x73, 0x73, 0x6f, 0x72, 0x73, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x51, 0x75, 0x69, 0x74,
	0x10, 0x03, 0x2a, 0x25, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x07, 0x0a, 0x03,
	0x57, 0x69, 0x6e, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x4c, 0x6f, 0x73, 0x65, 0x10, 0x01, 0x12,
	0x08, 0x0a, 0x04, 0x44, 0x72, 0x61, 0x77, 0x10, 0x02, 0x32, 0x3a, 0x0a, 0x04, 0x47, 0x61, 0x6d,
	0x65, 0x12, 0x32, 0x0a, 0x08, 0x50, 0x6c, 0x61, 0x79, 0x4d, 0x6f, 0x76, 0x65, 0x12, 0x10, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x1a,
	0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x23, 0x5a, 0x21, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x61, 0x64, 0x69, 0x2d, 0x31, 0x30, 0x32, 0x34, 0x2f, 0x72, 0x70,
	0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_protobuf_rps_proto_rawDescOnce sync.Once
	file_protobuf_rps_proto_rawDescData = file_protobuf_rps_proto_rawDesc
)

func file_protobuf_rps_proto_rawDescGZIP() []byte {
	file_protobuf_rps_proto_rawDescOnce.Do(func() {
		file_protobuf_rps_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_rps_proto_rawDescData)
	})
	return file_protobuf_rps_proto_rawDescData
}

var file_protobuf_rps_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_protobuf_rps_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protobuf_rps_proto_goTypes = []interface{}{
	(Moves)(0),       // 0: protobuf.Moves
	(Result)(0),      // 1: protobuf.Result
	(*Action)(nil),   // 2: protobuf.Action
	(*Response)(nil), // 3: protobuf.Response
}
var file_protobuf_rps_proto_depIdxs = []int32{
	0, // 0: protobuf.Action.move:type_name -> protobuf.Moves
	1, // 1: protobuf.Response.res:type_name -> protobuf.Result
	2, // 2: protobuf.Game.PlayMove:input_type -> protobuf.Action
	3, // 3: protobuf.Game.PlayMove:output_type -> protobuf.Response
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protobuf_rps_proto_init() }
func file_protobuf_rps_proto_init() {
	if File_protobuf_rps_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_rps_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Action); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_rps_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_rps_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuf_rps_proto_goTypes,
		DependencyIndexes: file_protobuf_rps_proto_depIdxs,
		EnumInfos:         file_protobuf_rps_proto_enumTypes,
		MessageInfos:      file_protobuf_rps_proto_msgTypes,
	}.Build()
	File_protobuf_rps_proto = out.File
	file_protobuf_rps_proto_rawDesc = nil
	file_protobuf_rps_proto_goTypes = nil
	file_protobuf_rps_proto_depIdxs = nil
}
